[routes]
tours.route = "tours/:action"
tours.defaults.module = curatescape
tours.defaults.controller = tours
tours.defaults.action = "browse"

tourAction.route = "tours/:action/:id"
tourAction.defaults.module = curatescape
tourAction.defaults.controller = tours
tourAction.defaults.action = "show"
tourAction.reqs.id = "\d+"
; redirects: see CuratescapeToursController showAction()
redirectDashShow.route = "curatescape-tours/:action/:id"
redirectDashShow.defaults.module = curatescape
redirectDashShow.defaults.controller = curatescape-tours
redirectDashShow.defaults.action = "show"
redirectDashShow.reqs.id = "\d+"

redirectSlashShow.route = "curatescape/tours/:action/:id"
redirectSlashShow.defaults.module = curatescape
redirectSlashShow.defaults.controller = curatescape-tours
redirectSlashShow.defaults.action = "show"
redirectSlashShow.reqs.id = "\d+"

; redirects: see CuratescapeToursController indexAction()
redirectSlashIndex.route = "curatescape/tours"
redirectSlashIndex.defaults.module = curatescape
redirectSlashIndex.defaults.controller = curatescape-tours
redirectSlashIndex.defaults.action = "index"

redirectDashIndex.route = "curatescape-tours"
redirectDashIndex.defaults.module = curatescape
redirectDashIndex.defaults.controller = curatescape-tours
redirectDashIndex.defaults.action = "index"

; redirects: see CuratescapeToursController browseAction()
redirectSlashBrowse.route = "curatescape/tours/:action"
redirectSlashBrowse.defaults.module = curatescape
redirectSlashBrowse.defaults.controller = curatescape-tours
redirectSlashBrowse.defaults.action = "browse"

redirectDashBrowse.route = "curatescape-tours/:action"
redirectDashBrowse.defaults.module = curatescape
redirectDashBrowse.defaults.controller = curatescape-tours
redirectDashBrowse.defaults.action = "browse"